### ISSUE TITLE
Query on the way your system handles vgg-16 network

### ISSUE THREAD

**Issue by JacksonZyy** [Verified-Intelligence/alpha-beta-CROWN#10]
Hi,

I wonder how do you handle vgg16 networks in your system.
And I noticed from prepare_instance.sh that you would call up dnnv to convert the maxpooling layer to relu.
So may I double-check that when your system verifies on vgg16, it verified on the converted network?
Thank you so much for your reply!

Best regards,
Yuyi

**Comment by shizhouxing** [comment]
Hi Yuyi @JacksonZyy , your understanding is right.
