### ISSUE TITLE
NotImplementedError when analysing on onnx network

### ISSUE THREAD

**Issue by JacksonZyy** [Verified-Intelligence/alpha-beta-CROWN#12]
Hi,

I tried to use your tool to analyze mnist_relu_6_100.onnx from ERAN system (https://files.sri.inf.ethz.ch/eran/nets/onnx/mnist/mnist_relu_6_100.onnx).
I used command `python abcrown.py --config exp_configs/mnist_6_100.yaml`
The yaml is as follows:
```
general:
  complete_verifier: bab-refine
model:
  name: mnist_6_100
  path: models/eran/mnist_relu_6_100.onnx
data:
  dataset: MNIST_ERAN_UN
  std: [1.0]
  mean: [0.0]
specification:
  epsilon: 0.025
attack:
  pgd_order: after
solver:
  batch_size: 1024
  beta-crown:
    iteration: 20
  mip:
    parallel_solvers: 16
    refine_neuron_time_percentage: 0.8
bab:
  timeout: 1000
  branching:
    reduceop: max
```
It returned me:
```
Traceback (most recent call last):
  File "abcrown.py", line 650, in <module>
    main()
  File "abcrown.py", line 553, in main
    verified_status, init_global_lb, lower_bounds, upper_bounds, refined_betas = mip(saved_bounds=saved_bounds)
  File "abcrown.py", line 145, in mip
    score=score, stop_criterion_func=stop_criterion_min(1e-4))
  File "/home/yuyi/alpha-beta-CROWN/complete_verifier/lp_mip_solver.py", line 1968, in build_the_model_mip_refine
    raise NotImplementedError
NotImplementedError
```
Could you please advise me why would this happen?

Thanks and regards,
Yuyi

**Comment by huanzhang12** [comment]
Some model files are accidentally missing in this release. I've just added it back.
You can clone the latest master and then run `python abcrown.py --config exp_configs/mnist_6_100.yaml`, and it should work now.

**Comment by JacksonZyy** [comment]
Hi,

Thanks for your reply.
The error I provided is NOT "FileNotFoundError: [Errno 2] No such file or directory"
It does work on the mnist_6_100_nat.pth model you provided.
But I wonder why it gives me NotImplementedError when I run on the original onnx model in the ERAN system (as I show in the original problem description).
Thank you!

**Comment by huanzhang12** [comment]
The onnx file has a weird normalization layer at the beginning, which was not handled in part of our code.
The converted pytorch file should work fine.

**Comment by JacksonZyy** [comment]
I see, thank you!
