### ISSUE TITLE
AssertionError when run conv model with sigmoid function

### ISSUE THREAD

**Issue by 13luoyu** [Verified-Intelligence/alpha-beta-CROWN#13]
Hello, I use your example file at 'exp_configs/cifar_conv_small_sigmoid.yaml' to run abcrown.py, then I got an assertion error:

File "/home/xue/alpha-beta-CROWN/complete_verifier/auto_LiRPA/backward_bound.py", line 760, in get_alpha_crown_start_nodes
    assert not sparse_intermediate_bounds or use_sparse_conv is False  # Double check our assumption holds. If this fails, then we created wrong shapes for alpha.
AssertionError

I wonder how to handle this?
Thank you.

**Comment by huanzhang12** [comment]
@13luoyu Thank you for reporting this to us! I just fixed it in the current master and `exp_configs/cifar_conv_small_sigmoid.yaml` should work now.

**Comment by 13luoyu** [comment]
Thanks for your reply. It works now.
