### ISSUE TITLE
UnsatisfiableError when creating conda environment using environment.yml

### ISSUE THREAD

**Issue by LIJYann** [Verified-Intelligence/alpha-beta-CROWN#15]
When creating conda environment using environment.yml, I am getting the following error:

Collecting package metadata (repodata.json): done
Solving environment: |
Found conflicts! Looking for incompatible packages.                                                                                                            
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package icu conflicts for:
fontconfig==2.13.1=h6c09931_0 -> libxml2[version='>=2.9.10,<2.10.0a0'] -> icu[version='>=58.2,<59.0a0']
matplotlib==3.5.1=py37h06a4308_1 -> pyqt -> qt=5.9 -> icu[version='>=58.2,<59.0a0']
gst-plugins-base==1.14.0=h8213a91_2 -> gstreamer[version='>=1.14.0,<2.0a0'] -> gettext -> libxml2[version='>=2.9.10,<2.10.0a0'] -> icu[version='>=58.2,<59.0a0']
keras==2.4.3=hd3eb1b0_0 -> tensorflow -> tensorflow-base==2.5.0=mkl_py37h35b2a3d_0 -> icu[version='>=68.1,<69.0a0']
scikit-image==0.19.2=py37h51133e4_0 -> networkx[version='>=2.2'] -> matplotlib[version='>=3.3'] -> matplotlib-base[version='>=3.5.1,<3.5.2.0a0'] -> icu[version='>=58.2,<59.0a0']
icu==58.2=he6710b0_3
pyqt==5.9.2=py37h05f1152_2 -> qt=5.9 -> icu[version='>=58.2,<59.0a0']
qt==5.9.7=h5867ecd_1 -> icu[version='>=58.2,<59.0a0']
libxml2==2.9.14=h74e7548_0 -> icu[version='>=58.2,<59.0a0']
keras-base==2.4.3=pyhd3eb1b0_0 -> tensorflow[version='>=2.2'] -> tensorflow-base==2.5.0=mkl_py37h35b2a3d_0 -> icu[version='>=68.1,<69.0a0']

How to deal with it? Thank you!

**Comment by huanzhang12** [comment]
I used the latest conda (22.11.1) and cannot reproduce this issue.
What is your OS and architecture? The environment was tested on Linux + x86-64 only. Windows, MacOS, and non-x86-64 are not officially supported.

**Comment by LIJYann** [comment]
Thanks for your responding. Here is my OS information:
Linux version 5.4.0-80-generic (buildd@lcy01-amd64-028) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04))
conda 4.7.11

I will try again with the latest conda and see if the problem can be solved.

**Comment by LIJYann** [comment]
The problem is solved with the latest miniconda, thanks for your responding. 

Besides, I've seen that in previous version, there exist a tutorial showing the work flow. Will there be a new one for this new version?

**Comment by huanzhang12** [comment]
@LIJYann You can start with this documentation: https://github.com/Verified-Intelligence/alpha-beta-CROWN/blob/main/complete_verifier/docs/abcrown_usage.md
