### ISSUE TITLE
Randomness of visited subdomains

### ISSUE THREAD

**Issue by JacksonZyy** [Verified-Intelligence/alpha-beta-CROWN#19]
Hi,

I just noticed that when running on the same network and the same property, the visited subdomains could be different.
```
all nodes are split!!
9651 domains visited
Result: timeout
Time: 111.90976047515869
```
```
all nodes are split!!
9777 domains visited
Result: timeout
Time: 112.87935328483582
```
```
all nodes are split!!
9790 domains visited
Result: timeout
Time: 114.08122301101685
```
For example, I presented the printouts of 3 executions given the same config (I set the attack as skip, and the bab timeout as 360)
Even though all nodes are split, I wonder why different numbers of domains were visited for different execution. 
What leads to this randomness of domains?
I would be grateful if you could share some insights.

Thanks and regards,
Yuyi

**Comment by huanzhang12** [comment]
This is normal because the optimization process of alpha/beta parameters may be slightly different each time, and there are domains that are very close to verify (bounds close to 0) so they are sensitive to optimization randomness.

**Comment by JacksonZyy** [comment]
@huanzhang12 Thanks for your reply!
