### ISSUE TITLE
Support for Softmax

### ISSUE THREAD

**Issue by mhmd97z** [Verified-Intelligence/alpha-beta-CROWN#22]
Hi,
I could not find any Softmax function in the provided demos. I wanted to confirm with you whether Softmax is supported or not.
Thanks!

**Comment by shizhouxing** [comment]
Hi @mhmd97z , it’s not supported in complete verification for now. We have incomplete verification and certified training on transformers with softmax: https://github.com/Verified-Intelligence/auto_LiRPA/blob/master/examples/language/train.py

**Comment by huanzhang12** [comment]
@shizhouxing BTW there is a recent research paper from Stanford and IBM on softmax verification and they also apply it to verify transformers. You should take a look https://arxiv.org/pdf/2303.01713.pdf

**Comment by mhmd97z** [comment]
Thank you for your replies.
