### ISSUE TITLE
Integer variables support

### ISSUE THREAD

**Issue by mhmd97z** [Verified-Intelligence/alpha-beta-CROWN#27]
Hi, I was wondering if it's possible to define integer or binary values in CROWN
Thanks!

**Comment by huanzhang12** [comment]
@mhmd97z Thanks for asking us. Currently, integer or binary values are not supported. We will consider adding binary value support in a future release. If you have any particular interesting problem that requires integer or binary support, please let us know, and we may be able to test and benchmark on it during development.
