### ISSUE TITLE
environment.yaml file for Mac OS

### ISSUE THREAD

**Issue by aferr** [Verified-Intelligence/alpha-beta-CROWN#37]
Hello and fantastic work on developing your tool!

I am just beginning to try it out, and want to try running it on a Mac OS computer. I have the impression that your environment.yaml file is for linux rather than Mac OS. I am wondering if you happen to already have an environment.yml file that works for Mac OS. (If not and I reach one that works, I will be happy to share it.)

**Comment by shizhouxing** [comment]
HI @aferr ,

We don't have an environment.yaml file macos yet. You may set up a conda environment by:
1. Installing [auto_LiRPA](https://github.com/Verified-Intelligence/auto_LiRPA#installation) along with its dependencies.
2. Installing additional dependencies required by alpha-beta-crown: https://github.com/Verified-Intelligence/alpha-beta-CROWN/blob/main/complete_verifier/requirements.txt

Please let us know if you find anything missing in requirements.txt or any other issue.
