### ISSUE TITLE
PackagesNotFoundError when Creating Conda Environment for alpha-beta-CROWN

### ISSUE THREAD

**Issue by r11942152** [Verified-Intelligence/alpha-beta-CROWN#39]
Dear alpha-beta-CROWN Team,

I hope this message finds you well. I've been working on running your latest version of Alpha-Beta-CROWN, but I've encountered a **PackagesNotFoundError** while executing the following command:

```
conda create -f complete_verifier/environment.yaml --name alpha-beta-crown
```
The following command will also show the same error:
```
conda create -f complete_verifier/environment_2022.yaml --name alpha-beta-crown
conda create -f complete_verifier/environment_pyt111.yaml --name alpha-beta-crown
conda create -f complete_verifier/environment_pyt200.yaml --name alpha-beta-crown
conda create -f complete_verifier/environment_pyt201.yaml --name alpha-beta-crown
```
The error message I received is as follows:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - complete_verifier/environment.yaml

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
I would greatly appreciate your guidance and support to help me overcome this issue. 

Thank you in advance for your help.

**System configuration:**
 - OS: 18.04.6 LTS
 - Have you tried to reproduce the problem in a cleanly created conda/virtualenv environment using official installation instructions and the latest code on the main branch?: Yes

**Comment by shizhouxing** [comment]
It should be `conda env create`, not `conda create`. See https://github.com/Verified-Intelligence/alpha-beta-CROWN#installation-and-setup.

**Comment by r11942152** [comment]
@shizhouxing It works. Thank you for your assistance!
