### ISSUE TITLE
Compatibility problems pytorch and onnx2pytorch

### ISSUE THREAD

**Issue by hugomh00** [Verified-Intelligence/alpha-beta-CROWN#4]
Hello, 
I am having some incompatibility issues at the moment with the alpha-beta-CROWN tool running the experiments for the VNNCOMP21 competition. 

I have created a conda environment with python 3.8 and I have installed the packages manually using the installation script provided. The command to install onnx2pytorch from Github did not work: git+git://github.com/Sarimuko/onnx2pytorch@8879f72c41ba960ff6495ae754d885eac2ebf656#egg=onnx2pytorch

So, I installed the pip package available for onnx2python (last version is 0.4.1). This package showed to have some incompatibilities with the pytorch version 1.8.2 (the last available at the pytorch-lts channel). Then I replaced this version by the pytorch version 1.11 for CUDA from the pytorch channel in Anaconda. Like this, the code worked but it still fails in some of the predefined benchmarks of the competition due to some of the torch modules that seem to be incompatible in some way with the code. 

My questions are:

Is there a pip package version for onnx2pytorch that matches (or being similar) the one of git+git://github.com/Sarimuko/onnx2pytorch@8879f72c41ba960ff6495ae754d885eac2ebf656#egg=onnx2pytorch?

Do you know what is the latest version of pytorch compatible with the alpha-beta-CROWN code?

I have attached the images with the command introduced to run the code, the errors obtained and the pytorch, onnx, CUDA, onnx2pytorch versions installed.

Thank you in advance.

![ErrorAlphaBeta](https://user-images.githubusercontent.com/48921860/166159883-d06534ac-b389-44c6-a017-4b1ebb5eeb5b.jpg)

![command_alphabeta](https://user-images.githubusercontent.com/48921860/166159888-62723c47-010c-49e1-baf4-94faf2969a5e.jpg)

![pytorchconda](https://user-images.githubusercontent.com/48921860/166159896-3bbdca79-91ec-4e31-bdae-3ff4dc1acdf9.PNG)
![onnx](https://user-images.githubusercontent.com/48921860/166159898-efd786b2-2e77-465e-b14c-9100b8df79dd.PNG)

**Comment by KaidiXu** [comment]
Hi,

Did you receive the error '[The unauthenticated git protocol on port 9418 is no longer supported](https://stackoverflow.com/questions/70663523/the-unauthenticated-git-protocol-on-port-9418-is-no-longer-supported)' when installing onnx2pytorch?

It can be fixed by using `git config --global url."https://github.com/".insteadOf git://github.com/` before ` pip install git+git://github.com/Sarimuko/onnx2pytorch@master#egg=onnx2pytorch`

Best,
Kaidi

**Comment by huanzhang12** [comment]
@hugomh00 I fixed the installation issue in a0ee4d84632300a7c3504378bef6068011e25511, please use the latest version and let us know if it still does not work.

Thanks,
Huan

**Comment by hugomh00** [comment]
Hello,
Thank you very much. It did work except for the nn4sys category.
![ErrorAlphaBeta](https://user-images.githubusercontent.com/48921860/166510336-0a515907-e9f2-4687-8aa3-49a1652db5a6.jpg)

**Comment by huanzhang12** [comment]
@hugomh00 You can use the latest version and follow the updated instruction [here](https://github.com/huanzhang12/alpha-beta-CROWN/blob/main/complete_verifier/docs/vnn_comp.md) and let us know if there are any remaining issues.
