### ISSUE TITLE
alpha-beta-crown always returns timeout even for a very simple model

### ISSUE THREAD

**Issue by kamdoumloich** [Verified-Intelligence/alpha-beta-CROWN#49]
Hi everyone,

We are currently trying to get a workflow involving neural network verification for networks that involve convolutional layers to run. Unfortunately, we are having little luck so far, because when skipping PGD-Attack, alpha-beta-crown always returns *timeout*. The result remained the same for "bab" and for "GCP-CROWN".

We defined a simple test case to allow the reproduction of our problem. Please can you tell us why we get "timeout" every time even for such a simple case? We Attached an example Jupyter notebook for learning and writing an ONNX-file, the resulting the ONNX file, the vnnlib-property file, theyaml-configuration file, and an image of the output we get.

The command we use to run alpha-beta-crown is as follow: 
```shell
python abcrown.py --config personal_config/onnx_with_one_vnnlib.yaml --timeout 100
```

[example_cnn.zip](https://github.com/Verified-Intelligence/alpha-beta-CROWN/files/14269586/example_cnn.zip)

**Comment by shizhouxing** [comment]
Hi @kamdoumloich , it's expected as the propertries you are trying to verify do not hold. If you turn on PGD (by not skipping the PGD attack), it will report that PGD attack succeeded, which means that counterexamples exist.

**Comment by jasperr** [comment]
I see this same problem even with attack_order: skip
