### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by mathisdon** [Verified-Intelligence/alpha-beta-CROWN#56]
I'm following the installation instructions, using miniconda with python 3.11 installed, on Windows. I get the error below. I must be doing something fundamentally wrong for it not to find so many packages. What am I doing wrong?

I did this:
> git clone --recursive https://github.com/Verified-Intelligence/alpha-beta-CROWN.git  (worked fine)
> conda env create -f complete_verifier/environment.yaml --name alpha-beta-crown

And the result was:

Channels:
 - gurobi
 - pytorch
 - nvidia
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - zstd==1.5.5=hc292b87_0
  - zlib==1.2.13=h5eee18b_0
  - yaml==0.2.5=h7b6447c_0
  - xz==5.4.6=h5eee18b_0
  - wheel==0.41.2=py311h06a4308_0
  - virtualenv==20.17.1=py311h06a4308_0
  - urllib3==2.1.0=py311h06a4308_0
  - ukkonen==1.0.1=py311hdb19cb5_0
  - typing_extensions==4.9.0=py311h06a4308_1
  - typing-extensions==4.9.0=py311h06a4308_1
  - tqdm==4.65.0=py311h92b7b1e_0
  - torchtriton==2.2.0=py311
  - tk==8.6.12=h1ccaba5_0
  - tbb==2021.8.0=hdb19cb5_0
  - sympy==1.12=py311h06a4308_0
  - sqlite==3.41.2=h5eee18b_0
  - setuptools==68.2.2=py311h06a4308_0
  - scipy==1.11.4=py311h08b1b3b_0
  - scikit-learn==1.2.2=py311h6a678d5_1
  - rich==13.3.5=py311h06a4308_0
  - requests==2.31.0=py311h06a4308_1
  - readline==8.2=h5eee18b_0
  - pyyaml==6.0.1=py311h5eee18b_0
  - pytz==2023.3.post1=py311h06a4308_0
  - pytorch-cuda==12.1=ha16c6d3_5
  - pytorch==2.2.1=py3.11_cuda12.1_cudnn8.9.2_0
  - python==3.11.8=h955ad1f_0
  - pytest==7.4.0=py311h06a4308_0
  - pygments==2.15.1=py311h06a4308_1
  - psutil==5.9.0=py311h5eee18b_0
  - pre-commit==3.4.0=py311h06a4308_1
  - pluggy==1.0.0=py311h06a4308_1
  - platformdirs==2.5.2=py311h06a4308_0
  - pip==23.3.1=py311h06a4308_0
  - pillow==10.2.0=py311h5eee18b_0
  - pandas==2.1.4=py311ha02d727_0
  - packaging==23.1=py311h06a4308_0
  - openssl==3.0.13=h7f8727e_0
  - openjpeg==2.4.0=h3ad879b_0
  - openh264==2.1.1=h4ff587b_0
  - onnxruntime==1.15.1=py311hcd73a83_0
  - onnx==1.13.1=py311h12ddb61_0
  - numpy-base==1.26.4=py311hf175353_0
  - numpy==1.26.4=py311h08b1b3b_0
  - numexpr==2.8.7=py311h65dcdc2_0
  - nodeenv==1.7.0=py311h06a4308_0
  - networkx==3.1=py311h06a4308_0
  - nettle==3.7.3=hbbd107a_1
  - ncurses==6.4=h6a678d5_0
  - mpmath==1.3.0=py311h06a4308_0
  - mpfr==4.0.2=hb69a4c5_1
  - mpc==1.1.0=h10f8cd9_1
  - mkl_random==1.2.4=py311hdb19cb5_0
  - mkl_fft==1.3.8=py311h5eee18b_0
  - mkl-service==2.4.0=py311h5eee18b_1
  - mkl==2023.1.0=h213fc3f_46344
  - mdurl==0.1.0=py311h06a4308_0
  - markupsafe==2.1.3=py311h5eee18b_0
  - markdown-it-py==2.2.0=py311h06a4308_1
  - lz4-c==1.9.4=h6a678d5_0
  - llvm-openmp==14.0.6=h9e868ea_0
  - libwebp-base==1.3.2=h5eee18b_0
  - libuuid==1.41.5=h5eee18b_0
  - libunistring==0.9.10=h27cfd23_0
  - libtiff==4.5.1=h6a678d5_0
  - libtasn1==4.19.0=h5eee18b_0
  - libstdcxx-ng==11.2.0=h1234567_1
  - libssh2==1.10.0=hdbd6064_2
  - libprotobuf==3.20.3=he621ea3_0
  - libpng==1.6.39=h5eee18b_0
  - libnghttp2==1.57.0=h2d74bed_0
  - libjpeg-turbo==2.0.0=h9bf148f_0
  - libidn2==2.3.4=h5eee18b_0
  - libiconv==1.16=h7f8727e_2
  - libgomp==11.2.0=h1234567_1
  - libgfortran5==11.2.0=h1234567_1
  - libgfortran-ng==11.2.0=h00389a5_1
  - libgcc-ng==11.2.0=h1234567_1
  - libffi==3.4.4=h6a678d5_0
  - libev==4.33=h7f8727e_1
  - libedit==3.1.20230828=h5eee18b_0
  - libdeflate==1.17=h5eee18b_1
  - libcurl==8.5.0=h251f7ec_0
  - libcufile==1.8.1.2=0
  - lerc==3.0=h295c915_0
  - ld_impl_linux-64==2.38=h1181459_1
  - lcms2==2.12=h3be6417_0
  - lame==3.100=h7b6447c_0
  - krb5==1.20.1=h143b758_1
  - jpeg==9e=h5eee18b_1
  - joblib==1.2.0=py311h06a4308_0
  - jinja2==3.1.3=py311h06a4308_0
  - intel-openmp==2023.1.0=hdb19cb5_46306
  - idna==3.4=py311h06a4308_0
  - identify==2.5.5=py311h06a4308_0
  - humanfriendly==10.0=py311h06a4308_1
  - gnutls==3.6.15=he1e5248_0
  - gmpy2==2.1.2=py311hc9b5ff0_0
  - gmp==6.2.1=h295c915_3
  - freetype==2.12.1=h4a9f257_0
  - filelock==3.13.1=py311h06a4308_0
  - ffmpeg==4.3=hf484d3e_0
  - distlib==0.3.6=py311h06a4308_0
  - coloredlogs==15.0.1=py311h06a4308_1
  - cfgv==3.4.0=py311h06a4308_0
  - cffi==1.16.0=py311h5eee18b_0
  - certifi==2024.2.2=py311h06a4308_0
  - ca-certificates==2023.12.12=h06a4308_0
  - c-ares==1.19.1=h5eee18b_0
  - bzip2==1.0.8=h7b6447c_0
  - bottleneck==1.3.7=py311hf4808d0_0
  - _openmp_mutex==5.1=1_gnu

Current channels:

  - https://conda.anaconda.org/gurobi/win-64
  - https://conda.anaconda.org/pytorch/win-64
  - https://conda.anaconda.org/nvidia/win-64
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/msys2/win-64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by shizhouxing** [comment]
Hi @mathisdon ,

It looks like you are using Windows? I guess environment.yaml we provided may not be compatible with Windows.

Alternatively, you may try using pip. There are two sets of dependencies that need to be installed:
1. Pytorch and auto_LiRPA, as specified at https://github.com/Verified-Intelligence/auto_LiRPA?tab=readme-ov-file#installation
2. Additional dependencies for the complete verifier: https://github.com/Verified-Intelligence/alpha-beta-CROWN/blob/main/complete_verifier/requirements.txt

**Comment by mathisdon** [comment]
Thank you, that worked.
But now I'm trying to run your example simple_verification.py and it can't import things from auto_LiRPA:
      
            9 import torch.nn as nn
           10 import torchvision
      ---> 11 from auto_LiRPA import BoundedModule, BoundedTensor
           12 from auto_LiRPA.perturbations import PerturbationLpNorm
           13 from auto_LiRPA.utils import Flatten
      
      ImportError: cannot import name 'BoundedModule' from 'auto_LiRPA' (unknown location)


But I can import auto_LiRPA by itself like this:
> import auto_LiRPA      (succeeds)

Is there further setup that I need to do?

Thanks

**Comment by shizhouxing** [comment]
@mathisdon Are you running the example from the auto_LiRPA/examples folder (is your current working directory `auto_LiRPA/examples`)?

**Comment by mathisdon** [comment]
> @mathisdon Are you running the example from the auto_LiRPA/examples folder (is your current working directory `auto_LiRPA/examples`)?

No I wasn't. I'll try that now.

**Comment by mathisdon** [comment]
That worked when I CD'd to the examples/vision directory and ran it from there like this:

python -m simple_verification

Thanks!
I don't fully understand the semantics of python modules so I don't know why it had to be run from what looks like *inside* the auto_LiRPA module. 

One last question: Is there a way to run it inside a Jupyter Notebook other than doing the following?

!python -m simple_verification

**Comment by shizhouxing** [comment]
>I don't fully understand the semantics of python modules so I don't know why it had to be run from what looks like inside the auto_LiRPA module

If you are at the alpha-beta-CROWN directory, it will try to import auto_LiRPA locally from alpha-beta-CROWN/auto_LiRPA, but actually we need to import from alpha-beta-CROWN/auto_LiRPA/auto_LiRPA. And when you are at auto_LiRPA/examples, it will import auto_LiRPA from the installed module so it can work.

>One last question: Is there a way to run it inside a Jupyter Notebook other than doing the following?

That's possible. You may need to copy the code to a notebook.

**Comment by mathisdon** [comment]
Ah of course, I see that now. The outer auto_LiRPA directory is not a module because it has no __init__.py file. But the inner auto_LiRPA does. And so examples/ is not inside the module, it's just inside the outer auto_LiRPA directory. Thanks.

**Comment by shizhouxing** [comment]
>Actually , I still don't understand how the python file inside the examples/vision directory knows about the auto_LiRPA module which is 2 level up the file hierarchy... :/

Because you have installed auto_LiRPA by running `pip install .` as instructed in the auto_LiRPA's installation guide. After that, you can import auto_LiRPA anywhere, just like you can import pytorch anywhere.

**Comment by mathisdon** [comment]
Ok, yes. Thanks for your patience with this elementary stuff, I greatly appreciate the help! I can probably take it from here.
