### ISSUE TITLE
How to run abcrown.py from inside Python?

### ISSUE THREAD

**Issue by mathisdon** [Verified-Intelligence/alpha-beta-CROWN#60]
Hi, I can run abcrown.py by following your tutorial_examples and calling it like this from the Linux command line:

`python abcrown.py --config exp_configs/tutorial_examples/cifar_resnet_2b.yaml`

But is there a recommended way to call it from inside Python? 
I see that abcrown.py has these lines at the end:

```
if __name__ == '__main__':
    abcrown = ABCROWN(args=sys.argv[1:])
    abcrown.main()
```

When I try to run it from inside python, `__name__` is not `__main__` and `sys.argv` is not set.
Is there a way to call it from another python module and capture its outputs?

**Comment by shizhouxing** [comment]
Hi @mathisdon , here is an example: https://github.com/Verified-Intelligence/Lyapunov_Stable_NN_Controllers/blob/main/neural_lyapunov_training/levelset.py We can create a `ABCROWN` instance with a list of arguments. Results can be captured from `verifier.logger`: https://github.com/Verified-Intelligence/Lyapunov_Stable_NN_Controllers/blob/main/neural_lyapunov_training/levelset.py#L93
