### ISSUE TITLE
It appears that there are missing indentations at line 501 and 502 in abcrown.py.

### ISSUE THREAD

**Issue by xiaoyuanpigo** [Verified-Intelligence/alpha-beta-CROWN#61]

**Comment by shizhouxing** [comment]
Hi @xiaoyuanpigo , thanks reporting it. But I think it's expected. https://github.com/Verified-Intelligence/alpha-beta-CROWN/blob/main/complete_verifier/abcrown.py#L501-L502 correspond to the for-loop https://github.com/Verified-Intelligence/alpha-beta-CROWN/blob/main/complete_verifier/abcrown.py#L343. All the properties in `batched_vnnlib` need to be verified. If no `unsafe-bab` or `unknown` happens for any of the properties in `batched_vnnlib`, the result is `safe`. `return 'safe'` happens after the for-loop is complete.
