### ISSUE TITLE
"NotImplementedError: bound_dynamic_forward is not implemented for BoundMaxPool(...)" encountered while attempting to run vnncomp23's vggnet16 benchmark

### ISSUE THREAD

**Issue by SaiMadhavanG** [Verified-Intelligence/alpha-beta-CROWN#64]
**Describe the bug**
Getting `NotImplementedError` while running the given [config file](https://github.com/Verified-Intelligence/alpha-beta-CROWN/blob/main/complete_verifier/exp_configs/vnncomp23/vggnet16.yaml) for the vggnet16 benchmark for both vnncomp22 and vnncomp23 competitions.

Complete error message:
`NotImplementedError: bound_dynamic_forward is not implemented for BoundMaxPool(name=/input.8, inputs=[/68], perturbed=True).`

**To Reproduce**
1. Prepare benchmarks
```sh
git clone https://github.com/ChristopherBrix/vnncomp2023_benchmarks.git
(cd vnncomp2023_benchmarks; ./setup.sh)
```
2. Run following command from `complete_verifier` directory:
```sh
python3 abcrown.py --config exp_configs/vnncomp23/vggnet16.yaml
```

Complete output log can be found [here](https://drive.google.com/file/d/1efbqE9sr6ZLKPeDsx6pH5ZdbkZJZ7NPn/view?usp=sharing).

**System configuration:**
 - OS: Ubuntu 22.04. 
 - Python version: Python 3.11.8
 - Pytorch Version: 2.2.1
 - Hardware: RTX 4090
 - Have you tried to reproduce the problem in a cleanly created conda/virtualenv environment using official installation instructions and the latest code on the main branch?: Yes

**Comment by shizhouxing** [comment]
Hi @SaiMadhavanG , the current version requires running a maxpool-to-relu script for the VGG model:
https://github.com/Verified-Intelligence/alpha-beta-CROWN/blob/main/vnncomp_scripts/prepare_instance.sh#L56-L65

We will release a new version of alpha-beta-CROWN which will no longer require this step.
