### ISSUE TITLE
Upper bound with Beta CROWN

### ISSUE THREAD

**Issue by mhmd97z** [Verified-Intelligence/alpha-beta-CROWN#66]
Hello, is it theoretically possible to calculate the upper bound of the output using Beta Crown? I'm asking this because upper bound calculation is disabled [here](https://github.com/Verified-Intelligence/alpha-beta-CROWN/blob/03adfa9c0bdd32efcb53d44e473552c70ecc5e3c/complete_verifier/beta_CROWN_solver.py#L331) in this method.

**Comment by shizhouxing** [comment]
It focuses on computing the lower bound. The problem of computing the upper bound can be converted to a lower bound problem: https://github.com/Verified-Intelligence/alpha-beta-CROWN/issues/53
