### ISSUE TITLE
Linear constraint on input variables

### ISSUE THREAD

**Issue by mhmd97z** [Verified-Intelligence/alpha-beta-CROWN#70]
Hello, 

I was wondering if it is possible to define a linear constraint on a pair of input variables in input splitting or beta-crown in the current software.

Thanks

**Comment by shizhouxing** [comment]
Hi @mhmd97z, 

You may add a constraint by adding an output variable which is computed from your constraint function.

See an example from the paper https://arxiv.org/pdf/2404.07956:

https://github.com/Verified-Intelligence/Lyapunov_Stable_NN_Controllers/blob/main/verification/specs/pendulum_output_feedback_0.vnnlib

`(assert (<= Y_1 0.07))` is a constraint, where `Y_1` is the value of Lyapunov function. The constraint means that we only need to verify the Lyapunov function with in a particular level set.
