### ISSUE TITLE
backward for bias

### ISSUE THREAD

**Issue by xiaoyuanpigo** [Verified-Intelligence/alpha-beta-CROWN#72]
Why is "bias=0" on line 198 of pooling.py in the auto-LiRPA/operators folder? Shouldn't it be bias=last_bias instead?"

Thanks.

**Comment by Winlere** [comment]
The `bias` variable in `_bound_oneside()` functions is the local accumulated scalar value generated by plugging in linear relaxations of $\hat z$, and it will be evetually returned to `backward_general` and get added to the `lb` or `ub` variables living backward_bound.py: 283 - 404. I guess `last_bias` you mentioned refers to this.
