### ISSUE TITLE
How to cite KFSB?

### ISSUE THREAD

**Issue by jamesjingqili** [Verified-Intelligence/alpha-beta-CROWN#73]
If we want to cite the KFSB method, then which paper should we cite? I tried to search a lot, but I can only find the paper that proposed FSB. Any pointer will be appreciated. Thanks!

**Comment by huanzhang12** [comment]
KFSB is just a small variation of FSB. It picks the top-k neurons among all layers to evaluate, whereas the original FSB score picks the top-k neuron for each layer, and thus can be a bit slow when the network has many layers. For efficiency, we use KFSB by default. If I recall correctly, this heuristic was introduced in our VNN-COMP 2021 submission to address the high overhead of branching heuristics. You can still cite the original FSB paper and mention that α,β-CROWN has a variation of FSB to improve its efficiency on deeper networks.

**Comment by jamesjingqili** [comment]
Thank you very much for your timely reply!
