### ISSUE TITLE
auto_LiRPA installlation fails with python 3.12

### ISSUE THREAD

**Issue by yizhake** [Verified-Intelligence/alpha-beta-CROWN#81]
I try to install auto_LiRPA on ubunto 24.04 LTS using 
`pip install auto-LiRPA==0.3
`
and get the following error message:
```
Collecting auto-LiRPA==0.3
  Using cached auto_LiRPA-0.3-py3-none-any.whl.metadata (15 kB)
INFO: pip is looking at multiple versions of auto-lirpa to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement torch<1.13.0,>=1.8.0 (from auto-lirpa) (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.5.1)
ERROR: No matching distribution found for torch<1.13.0,>=1.8.0
```
But my torch version is 2.5.1 (`pip show torch`), and trying to downgrade it with
`pip install torch==1.12.0`
fails with this error meassge:
```
ERROR: Could not find a version that satisfies the requirement torch==1.12.0 (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.5.1)
ERROR: No matching distribution found for torch==1.12.0
```
I see that torch==1.12.0 is supported in python 3.7.3-3.10.x, but I have python 3.12.3 where the minimal torch version is 2.2.0.
Any ideas?

Thanks in advance, Yizhak.

**Comment by shizhouxing** [comment]
You may try installing the latest version (version 0.5) at
https://github.com/Verified-Intelligence/auto_LiRPA/tree/bfb7997115c5e66327de81b43c42b23c8a0ffb1e/auto_LiRPA
